export const routerLinks = (name: string, type?: string) => {
    const array: {
        [selector: string]: string;
    } = {
        Login: '/auth/login',
        Register: '/auth/register',
        ForgetPassword: '/forgot-password',
        VerifyForotPassword: '/verify-forgot-password',
        SetPassword: '/set-password',
        MyProfile: '/my-profile',
        User: '/users',
        Setting: '/setting',
        Data: '/signin-permission',
        DataType: '/setting/data/type',
        Post: '/post',
        PostType: '/setting/post/type',
        Code: '/danh-muc',
        Parameter: '/parameters',
        Navigation: '/navigation',
        Folders: '/folders',
        Test: '/test',
        PurchaseOrderReturn: '/purchase-order-return',
        SalesOrderReturn: '/sales-order-return',
        RightMapRole: '/permissions',
        // MANH KHANH
        NhomVatTu: '/nhom-vat-tu',
        VatTu: '/product',
        NhaCungCap: '/nha-cung-cap',
        SanPham: '/san-pham',
        BOM: '/bom',
        PurchaseOrder: '/purchase-orders',
        SaleOrder: '/sale-orders',
        DuAn: '/du-an',
        KhachHang: '/khach-hang',
        Roles: '/quan-ly-nhom-nguoi-dung',
        PhieuNhap: '/phieu-nhap',
        PhieuXuat: '/phieu-xuat',
        ChiPhi: '/payment_vouchers',
        PhieuThu: '/receipt_vouchers',
        QuanLyThu: '/receipt-management',
        vouchers: '/reports/vouchers',
        PhienKiemKho: '/inventory-check-note',
        WarehouseTransferNote: '/warehouse-transfer-note',
        BaoGia: '/bao-gia',
        ThongKe: '/stock-transaction',
        NgayLamViec: '/ngay-lam-viec',
        SocialInsurance: '/social-insurance',
        BangChamCong: '/bang-cham-cong',
        BangTinhLuong: '/bang-tinh-luong',
        CauHinhNhanSu: '/cau-hinh-nhan-su',
        Product: '/product',
        Quotation: '/quotationv2',
        StockTransaction: '/stock-transaction',
        CustomerDebtReport: '/customer-debt-report', // Báo cáo công nợ khách hàng
        SupplierDebtReport: '/supplier-debt-report', // Báo cáo công nợ nhà cung cấp
        InventoryReceipt: '/inventory-receipt', //Phiếu nhập kho
        InventoryIssue: '/inventory-issue', //Phiếu xuất kho
        DashboardVisualize: '/dashboard-visualize',
        ReportsFinance: '/reports/finance', // danh sách báo cáo tài
        lSCS: '/customer-service',
        EInvoice: '/e-invoices', // Quản lý hóa đơn điện tử
        CashFlowReport: '/cash_flow_report', // Báo cáo dòng tiền
        Construction: '/construction', // Quản lý công trình dự án
        Contract: '/contracts', // Quản lý hợp đồng/Phụ lục
        IssueManagement: '/issue-management',
        CashbookDashboard: '/cashbook-dashboard',
        MaterialRequest: '/material-request',
        Tenant: '/tenants',
        Feedback: '/feedback',
        QuanLyTaiSan: '/quan-ly-tai-san',
        BaoTriTaiSan: '/bao-tri-tai-san',
        LichBaoTri: '/lich-bao-tri',
        ThanhLyTaiSan: '/thanh-ly-tai-san',
        TaskManagement: '/task-management',
        AdvanceRequest: '/advance-requests',
        AssetType: '/asset-type',
        AssetGroup: '/asset-group',
        MeasureUnit: '/measure-unit',
        AssetLocation: '/asset-location',
        ChartOfAccount: '/chart-of-accounts', // Phân loại thu, chi
        CashAndBank: '/cash-and-bank',
        VehicleRequest: '/vehicle-request',
        Xe: '/qly-xe',
        LaiXe: '/quan-ly-lai-xe',
        Kho: '/kho',
        LoaiXe: '/qly-loai-xe',
        ConstructionSocialMedia: '/social-media',

        /// Danh mục
        VoltageType: '/voltage-type', // Loại cấp điện áp
        OwnerType: '/owner-type', // Loại chủ đầu tư
        ConsultService: '/consult-service', // Loại dịch vụ tư vấn
        CarType: '/car-type', // Loại xe
        Car: '/car',
        PhongBan: '/phong-ban',
        ChucVu: '/chuc-vu',
        ProcessTemplate: '/process-template',
        Investor: '/investor',
        ProjectTemplate: '/project-template',
        Task: '/task',
        Project: '/projects',
        SystemUserAdmin: '/system-user-admin',
        ResourceView: '/resource-view',

        Dashboard: '/dashboard',
        Transactions: '/transactions',
        Budget: '/budget',
        Reports: '/reports',
        Wallets: '/wallets',
    }; // 💬 generate link to here
    const apis: {
        [selector: string]: string;
    } = {
        Auth: '/auth',
        TypesCodeTypeManagement: '/admin/code-type/types',
        ChartOfAccountCodeTypeManagement: '/admin/code-type/chart-of-accounts',
        CodeTypeManagement: '/admin/code-types',
        CodeType: '/code-type',
        Data: '/admin/data',
        DataType: '/admin/datatype',
        Role: '/idm/roles',
        User: '/idm/users',
        Post: '/admin/posts',
        Parameter: '/parameters',
        PostType: '/admin/post-categories',
        Navigation: '/bsd/navigations',
        Folders: '/folders',
        Bin: '/bin',
        Files: '/files',
        ObjMapUser: '/obj-map/user',
        ChucDanh: '/chuc-danh',
        // MANH KHANH
        PhongBan: '/phong-ban',
        ChucVu: '/chuc-vu',
        NhomVatTu: '/nhom-vat-tu',
        VatTu: '/product',
        SalesOrder: '/sales-orders',
        NhaCungCap: '/suppliers',
        SanPham: '/san-pham',
        IssueManagement: '/issue-management',
        BOM: '/bom',
        DuAn: '/du-an',
        KhachHang: '/customers',
        Roles: '/idm/roles',
        LSCS: '/lich-su-cham-soc',
        PurchaseOrder: '/purchase-orders',
        ThuChi: '/cashbook_transaction',
        PhienKiemKho: '/inventory-check-note',
        WarehouseTransferNote: '/warehouse-transfer-note',
        BaoGia: '/baogia',
        ThongKe: '/thong-ke',
        NgayLamViec: '/working-day',
        SocialInsurance: '/bhxh',
        BangChamCong: '/cham-cong',
        BangTinhLuong: '/bang-tinh-luong',
        CauHinhNhanSu: '/cau-hinh-nhan-su',
        Quotation: '/quotation',
        StockTransaction: '/statiscal/stock-transaction',
        DebtTransaction: '/debt-transactions',
        PurchaseOrderReturn: '/supplier-return',
        SalesOrderReturn: '/customer-return',
        InventoryNote: '/inventory-notes',
        Rights: '/idm/rights',
        RightMapRole: '/idm/right-map-role',
        Chatbot: '/chatbot',
        DashboardVisualize: '/dashboard-visualize',
        CustomerServiceComment: '/customer-service-comment',
        EInvoice: '/e-invoices',
        Construction: '/construction',
        Contract: '/contracts',
        QuanLyTaiSan: '/asset',
        BaoTriTaiSan: '/asset-maintenance',
        ThanhLyTaiSan: '/asset-liquidation',
        Tenant: '/admin/tenants',
        Feedback: '/feedback',
        MaterialRequest: '/material-request',
        AdvanceRequest: '/advance-requests',
        AssetType: '/asset-type',
        AssetGroup: '/asset-group',
        TaskManagement: '/task-management',
        MeasureUnit: '/measure-unit',
        AssetLocation: '/asset-location',
        AssetAllocation: '/asset-allocation',
        CashAndBank: '/cash_and_bank',
        ConstructionSocialMedia: '/social-media',
        Xe: '/quan-ly-phuong-tien',
        VehicleRequest: '/vehicle-request',
        LaiXe: '/quan-ly-lai-xe',
        LoaiXe: '/quan-ly-loai-xe',
        ProjectTemplate: '/project-template',
        Investor: '/investor',
        InvestorType: '/investor-type',
        WeekReport: '/week-report',
        Task: '/task',
        CommentTask: '/task-comment',
        TaskNotification: '/task-notification',
        Project: '/projects',
        SystemUserSub: '/system-user-sub',
        ResourceView: '/resource-view',

        Transactions: '/transactions',
    }; // 💬 generate api to here
    switch (type) {
        case 'api':
            return apis[name];
        default:
            return array[name];
    }
};
